name: My Workflow

on:
  push:
    branches:
      - Dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Git Pull
        run: git pull

      - name: Restart nginx
        run: sudo systemctl restart nginx
